# sanshanblog  后台
#需要与mongodb，mysql容器连接
# VERSION   1.0.Beta 
FROM nginx:1.13.3

LABEL maintainer="85432173@qq.com"
 
# COPY 配置文件 
COPY nginx.conf  /etc/nginx

ADD assets.tar.gz  /etc/nginx/html

# 暴露端口
EXPOSE 80

 


 
 
 